# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download

builds:
  - id: chatto
    binary: chatto
    main: ./cmd/chatto/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: chatto-cli
    binary: chatto-cli
    main: ./cmd/cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

dockers:
  - id: chatto
    image_templates:
      - "jaimeteb/chatto:{{ .Version }}-amd64"
    use_buildx: true
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: chatto
    image_templates:
      - "jaimeteb/chatto:{{ .Version }}-arm64v8"
    use_buildx: true
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"

docker_manifests:
  - id: chatto
    name_template: "jaimeteb/chatto:{{ .Version }}"
    image_templates:
      - "jaimeteb/chatto:{{ .Version }}-amd64"
      - "jaimeteb/chatto:{{ .Version }}-arm64v8"
  - id: chatto
    name_template: "jaimeteb/chatto:latest"
    image_templates:
      - "jaimeteb/chatto:{{ .Version }}-amd64"
      - "jaimeteb/chatto:{{ .Version }}-arm64v8"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
