language: go

go:
  - "1.15"

env:
  - GO111MODULE=on

install:
  - go mod tidy

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'pass'
  # - export REDIS_HOST=localhost
  # - export REDIS_PASS=pass

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
