language: go

env:
  - GO111MODULE=on

install:
  - go mod tidy

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'pass'
  # - export REDIS_HOST=localhost
  # - export REDIS_PASS=pass

script:
 - go run examples/00_test/ext/ext.go &
 - go run examples/03_pokemon/ext/ext.go -port 6770 &
 - go test ./fsm ./clf ./bot ./ext -cover -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
