name: firebase deploy merge

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/**'

env:
  PYTHON_VERSION: 3.9

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      -
        name: Install Python dependencies
        run: |
          pip install \
            mkdocs==1.4.2 \
            mkdocs-material==9.0.3
      -
        name: Build documentation
        run: |
          mkdocs build --clean
      -
        name: Firebase deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JAIMETEB }}'
          channelId: live
          projectId: jaimeteb
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
